---
driver:
  name: docker
  binary: docker
  use_sudo: false

provisioner:
  name: ansible_push
  idempotency_test: false
  verbose: "v" # verbose level v, vv, vvv, vvvv
  chef_bootstrap_url: nil

verifier:
  name: serverspec
  remote_exec: false

platforms:
  - name: ubuntu-promoted-builds-jenkins
    provisioner:
      mygroup: 
      - promoted-builds
      playbook: jenkins-promoted-builds.yml
    driver_config:
      provision_command:
      - apt-get update
      - apt-get upgrade -y
      - apt-get -q -y install python 
      image: ubuntu:16.04
      forward: 
        - 8080
suites:
  - name: default
    verifier:
      patterns:
        - test/integration/default/serverspec/*_spec.rb

