---
driver:
  name: docker
  binary: docker
  use_sudo: false


provisioner:
  name: ansible_playbook

platforms:
  #- name: ubuntu-14.04
  - name: centos-7.2

suites:
  - name: default
    run_list:
    attributes:
