---
driver:
  name: docker
  binary: docker
  use_sudo: false

provisioner:
  name: ansible_push
  playbook: produccion.yml
  #extra_vars: "@test_vars.yml"
  idempotency_test: True
  verbose: "v" # verbose level v, vv, vvv, vvvv
  chef_bootstrap_url: nil

verifier:
  name: serverspec
  remote_exec: false

platforms:
  - name: ubuntu-promoted-builds-jenkins
    provisioner:
      mygroup: 
      - promoted-builds
    driver_config:
      provision_command:
      - apt-get update
      - apt-get upgrade
      - apt-get -q -y install python 
      image: ubuntu:16.04
      forward: 
        - 8080
  - name: ubuntu-16.04
    driver_config:
      provision_command:
      - apt-get -q -y install python
      image: ubuntu:16.04
      forward: 
        - 8080
        - 22
  - name: centos-7
    driver_config:
      image: centos:7
      dockerfile: dockerfiles/Dockerfile.centos7
      forward: 
        - 8080
        - 22

suites:
  - name: default
    verifier:
      patterns:
        - test/integration/default/serverspec/*_spec.rb

