---
driver:
  name: docker
  binary: docker
  use_sudo: false

provisioner:
  name: ansible_push
  playbook: produccion.yml
  idempotency_test: True

platforms:
  #- name: ubuntu-14.04
  - name: centos-7.2

suites:
  - name: default
    provisioner:
      mygroup: webservers
