---
driver:
  name: vagrant


provisioner:
  name: ansible_push
  playbook: produccion.yml
  hosts: webservers
  idempotency_test: True
  chef_bootstrap_url: nil

platforms:
  #- name: ubuntu-14.04
  - name: centos-7.2

suites:
  - name: default
    hosts: webservers
