---
- hosts: promoted-builds
  become: true
  roles:
  - library/geerlingguy.jenkins
  tasks:
  - name: restart jenkins
    service: name=jenkins state=restarted
  - name: Wait for Jenkins to start up before proceeding.
    shell: "curl -D - --silent --max-time 5 http://{{ jenkins_hostname }}:{{ jenkins_http_port }}{{ jenkins_url_prefix }}/cli/"
    register: result
    until: (result.stdout.find("403 Forbidden") != -1) or (result.stdout.find("200 OK") != -1) and (result.stdout.find("Please wait while") == -1)
    retries: "{{ jenkins_connection_retries }}"
    delay: "{{ jenkins_connection_delay }}"
    changed_when: false
    check_mode: no
  - name: Install common dependencies
    package:
      name: "{{ item }}"
      state: present
    with_items: "{{ common_packages }}"
  - name: config jenkins devops-compile job
    jenkins_job:
      config: "{{ lookup('file', 'templates/devops-compile.xml') }}"
      name: devops-compile
      url: "http://{{ jenkins_hostname }}:{{ jenkins_http_port }}{{ jenkins_url_prefix }}"
      user: "{{ jenkins_admin_username }}"
      password: "{{ jenkins_admin_password }}"
  - name: Configure approvers 
    copy:
      src: templates/approvers.properties
      dest: /var/lib/jenkins/secrets/approvers.properties
      owner: "{{ jenkins_process_user }}"
      mode: 0644
  - name: Configure promotions dir
    file:
      path: /var/lib/jenkins/jobs/devops-compile/promotions/Deploy
      state: directory
      owner: "{{ jenkins_process_user }}"
  - name: Configure promotions
    copy:
      src: templates/devops-compile-promotion-deploy.xml
      dest: /var/lib/jenkins/jobs/devops-compile/promotions/Deploy/config.xml
      owner: "{{ jenkins_process_user }}"
      mode: 0644
  - name: config jenkins jobs
    jenkins_job:
      config: "{{ lookup('template', 'templates/pipeline-template.xml.j2') }}"
      name: "{{ item.name }}"
      url: "http://{{ jenkins_hostname }}:{{ jenkins_http_port }}{{ jenkins_url_prefix }}"
      password: "{{ jenkins_admin_password }}"
      user: "{{ jenkins_admin_username }}"
    with_items: "{{ pipeline }}"
