---
- hosts: promoted-builds
  become: true
  roles:
  - library/geerlingguy.jenkins
  tasks:
  - name: Install common dependencies
    package:
      name: "{{ item }}"
      state: present
    with_items: "{{ common_packages }}"
  - name: config jenkins devops-compile job
    jenkins_job:
      config: "{{ lookup('file', 'templates/devops-compile.xml') }}"
      name: devops-compile
      url: "http://{{ jenkins_hostname }}:{{ jenkins_http_port }}{{ jenkins_url_prefix }}"
      password: "{{ jenkins_admin_username }}"
      user: "{{ jenkins_admin_password }}"
  - name: Configure approvers 
    copy:
      src: templates/approvers.ini
      dest: /var/lib/jenkins/secrets/approvers.ini
      owner: "{{ jenkins_process_user }}"
      mode: 0644
  - name: Configure promotions dir
    file:
      path: /var/lib/jenkins/jobs/devops-compile/promotions/Deploy
      state: directory
      owner: "{{ jenkins_process_user }}"
  - name: Configure promotions
    copy:
      src: templates/devops-compile-promotion-deploy.xml
      dest: /var/lib/jenkins/jobs/devops-compile/promotions/Deploy/config.xml
      owner: "{{ jenkins_process_user }}"
      mode: 0644
